import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import { Syne, Noto_Sans } from 'next/font/google';

const syne = Syne({
  weight: '600',
  subsets: ['latin'],
  variable: '--font-syne',
});

const notoSans = Noto_Sans({
  weight: '100',
  subsets: ['latin'],
  variable: '--font-noto-sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${syne.variable} ${notoSans.variable}`}>
      <body>
          {children}
      </body>
    </html>
  );
}
